# --- Mutations ---

mutation SyncPreferences(
  $userUid: UUID!
  $firstVisit: Boolean!
  $travelingWith: String!
  $interests: [String!]!
  $updatedAt: DateTime!
) {
  syncUserPreference(
    userUid: $userUid
    firstVisit: $firstVisit
    travelingWith: $travelingWith
    interests: $interests
    updatedAt: $updatedAt
  ) {
    ok
  }
}

mutation ForgetMe($userUid: UUID!) {
  forgetMe(userUid: $userUid) {
    ok
  }
}

mutation RegisterFcmDevice(
  $registrationId: String!
  $type: String!
  $userUid: UUID
  $name: String
  $language: String
) {
  registerFcmDevice(
    registrationId: $registrationId
    type: $type
    userUid: $userUid
    name: $name
    language: $language
  ) {
    message
    ok
  }
}

